// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assignee_performance.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findAssigneesWithHighBlockedTime = `-- name: FindAssigneesWithHighBlockedTime :many
SELECT 
    assignee_username,
    issues_assigned,
    total_blocked_hours,
    ROUND((100.0 * total_blocked_hours / NULLIF(total_hours_as_assignee, 0))::numeric, 2) AS blocked_pct
FROM vw_individual_performance_metrics
WHERE project_id = $1
  AND total_blocked_hours > 50
ORDER BY blocked_pct DESC NULLS LAST
`

type FindAssigneesWithHighBlockedTimeRow struct {
	AssigneeUsername  interface{}    `json:"assignee_username"`
	IssuesAssigned    int64          `json:"issues_assigned"`
	TotalBlockedHours pgtype.Numeric `json:"total_blocked_hours"`
	BlockedPct        pgtype.Numeric `json:"blocked_pct"`
}

// Identify assignees spending too much time in BLOCKED state.
func (q *Queries) FindAssigneesWithHighBlockedTime(ctx context.Context, projectID int32) ([]FindAssigneesWithHighBlockedTimeRow, error) {
	rows, err := q.db.Query(ctx, findAssigneesWithHighBlockedTime, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAssigneesWithHighBlockedTimeRow{}
	for rows.Next() {
		var i FindAssigneesWithHighBlockedTimeRow
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.IssuesAssigned,
			&i.TotalBlockedHours,
			&i.BlockedPct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssigneeCycleTimeByIssue = `-- name: GetAssigneeCycleTimeByIssue :many
SELECT issue_id, issue_iid, project_id, assignee_username, active_cycle_hours, in_progress_hours, qa_review_hours, blocked_hours, backlog_hours, total_hours_as_assignee, contributed_active_work FROM vw_assignee_cycle_time WHERE issue_id = $1 ORDER BY active_cycle_hours DESC NULLS LAST
`

// Get cycle time breakdown for each assignee on a specific issue.
func (q *Queries) GetAssigneeCycleTimeByIssue(ctx context.Context, issueID int32) ([]VwAssigneeCycleTime, error) {
	rows, err := q.db.Query(ctx, getAssigneeCycleTimeByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwAssigneeCycleTime{}
	for rows.Next() {
		var i VwAssigneeCycleTime
		if err := rows.Scan(
			&i.IssueID,
			&i.IssueIid,
			&i.ProjectID,
			&i.AssigneeUsername,
			&i.ActiveCycleHours,
			&i.InProgressHours,
			&i.QaReviewHours,
			&i.BlockedHours,
			&i.BacklogHours,
			&i.TotalHoursAsAssignee,
			&i.ContributedActiveWork,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssigneeCycleTimeByProject = `-- name: GetAssigneeCycleTimeByProject :many
SELECT 
    assignee_username,
    COUNT(DISTINCT issue_id) AS issues_count,
    ROUND(SUM(active_cycle_hours)::numeric, 2) AS total_active_hours,
    ROUND(AVG(active_cycle_hours)::numeric, 2) AS avg_active_hours,
    ROUND(SUM(in_progress_hours)::numeric, 2) AS total_dev_hours,
    ROUND(SUM(qa_review_hours)::numeric, 2) AS total_qa_hours
FROM vw_assignee_cycle_time
WHERE project_id = $1
GROUP BY assignee_username
ORDER BY total_active_hours DESC NULLS LAST
`

type GetAssigneeCycleTimeByProjectRow struct {
	AssigneeUsername interface{}    `json:"assignee_username"`
	IssuesCount      int64          `json:"issues_count"`
	TotalActiveHours pgtype.Numeric `json:"total_active_hours"`
	AvgActiveHours   pgtype.Numeric `json:"avg_active_hours"`
	TotalDevHours    pgtype.Numeric `json:"total_dev_hours"`
	TotalQaHours     pgtype.Numeric `json:"total_qa_hours"`
}

// Get all assignee cycle time metrics for a project.
func (q *Queries) GetAssigneeCycleTimeByProject(ctx context.Context, projectID int32) ([]GetAssigneeCycleTimeByProjectRow, error) {
	rows, err := q.db.Query(ctx, getAssigneeCycleTimeByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssigneeCycleTimeByProjectRow{}
	for rows.Next() {
		var i GetAssigneeCycleTimeByProjectRow
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.IssuesCount,
			&i.TotalActiveHours,
			&i.AvgActiveHours,
			&i.TotalDevHours,
			&i.TotalQaHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssigneeWorkDistribution = `-- name: GetAssigneeWorkDistribution :many
SELECT 
    assignee_username,
    ROUND(SUM(active_cycle_hours)::numeric, 2) AS active_hours,
    ROUND(SUM(total_hours_as_assignee - COALESCE(active_cycle_hours, 0))::numeric, 2) AS wait_hours,
    ROUND((100.0 * SUM(active_cycle_hours) / NULLIF(SUM(total_hours_as_assignee), 0))::numeric, 2) AS active_pct
FROM vw_assignee_cycle_time
WHERE project_id = $1
GROUP BY assignee_username
ORDER BY active_pct DESC NULLS LAST
`

type GetAssigneeWorkDistributionRow struct {
	AssigneeUsername interface{}    `json:"assignee_username"`
	ActiveHours      pgtype.Numeric `json:"active_hours"`
	WaitHours        pgtype.Numeric `json:"wait_hours"`
	ActivePct        pgtype.Numeric `json:"active_pct"`
}

// Get distribution of active vs wait time for each assignee.
func (q *Queries) GetAssigneeWorkDistribution(ctx context.Context, projectID int32) ([]GetAssigneeWorkDistributionRow, error) {
	rows, err := q.db.Query(ctx, getAssigneeWorkDistribution, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssigneeWorkDistributionRow{}
	for rows.Next() {
		var i GetAssigneeWorkDistributionRow
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.ActiveHours,
			&i.WaitHours,
			&i.ActivePct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHighPerformers = `-- name: GetHighPerformers :many
SELECT 
    assignee_username,
    issues_contributed,
    total_active_cycle_hours,
    avg_active_cycle_per_issue,
    active_work_pct,
    p50_active_cycle_hours,
    p95_active_cycle_hours
FROM vw_individual_performance_metrics
WHERE project_id = $1
  AND issues_contributed >= 5
ORDER BY total_active_cycle_hours DESC NULLS LAST
LIMIT 20
`

type GetHighPerformersRow struct {
	AssigneeUsername       interface{}    `json:"assignee_username"`
	IssuesContributed      int64          `json:"issues_contributed"`
	TotalActiveCycleHours  pgtype.Numeric `json:"total_active_cycle_hours"`
	AvgActiveCyclePerIssue pgtype.Numeric `json:"avg_active_cycle_per_issue"`
	ActiveWorkPct          pgtype.Numeric `json:"active_work_pct"`
	P50ActiveCycleHours    pgtype.Numeric `json:"p50_active_cycle_hours"`
	P95ActiveCycleHours    pgtype.Numeric `json:"p95_active_cycle_hours"`
}

// Get top performers by active work percentage and volume.
func (q *Queries) GetHighPerformers(ctx context.Context, projectID int32) ([]GetHighPerformersRow, error) {
	rows, err := q.db.Query(ctx, getHighPerformers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetHighPerformersRow{}
	for rows.Next() {
		var i GetHighPerformersRow
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.IssuesContributed,
			&i.TotalActiveCycleHours,
			&i.AvgActiveCyclePerIssue,
			&i.ActiveWorkPct,
			&i.P50ActiveCycleHours,
			&i.P95ActiveCycleHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndividualPerformanceMetrics = `-- name: GetIndividualPerformanceMetrics :many
SELECT assignee_username, project_id, issues_assigned, issues_contributed, total_active_cycle_hours, avg_active_cycle_per_issue, total_dev_hours, total_qa_hours, total_blocked_hours, total_backlog_hours, active_work_pct, total_hours_as_assignee, high_cycle_time_issues, p50_active_cycle_hours, p95_active_cycle_hours FROM vw_individual_performance_metrics 
WHERE project_id = $1 
ORDER BY total_active_cycle_hours DESC NULLS LAST
`

// Get aggregated performance metrics for all assignees in a project.
func (q *Queries) GetIndividualPerformanceMetrics(ctx context.Context, projectID int32) ([]VwIndividualPerformanceMetric, error) {
	rows, err := q.db.Query(ctx, getIndividualPerformanceMetrics, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VwIndividualPerformanceMetric{}
	for rows.Next() {
		var i VwIndividualPerformanceMetric
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.ProjectID,
			&i.IssuesAssigned,
			&i.IssuesContributed,
			&i.TotalActiveCycleHours,
			&i.AvgActiveCyclePerIssue,
			&i.TotalDevHours,
			&i.TotalQaHours,
			&i.TotalBlockedHours,
			&i.TotalBacklogHours,
			&i.ActiveWorkPct,
			&i.TotalHoursAsAssignee,
			&i.HighCycleTimeIssues,
			&i.P50ActiveCycleHours,
			&i.P95ActiveCycleHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPerformanceOverTime = `-- name: GetUserPerformanceOverTime :many
SELECT 
    ac.assignee_username,
    DATE_TRUNC('month', ie.event_timestamp)::date AS month,
    COUNT(DISTINCT ac.issue_id) AS issues_completed,
    ROUND(SUM(ac.active_cycle_hours)::numeric, 2) AS total_active_hours,
    ROUND(AVG(ac.active_cycle_hours)::numeric, 2) AS avg_active_hours
FROM vw_assignee_cycle_time ac
JOIN issue_events ie ON ie.issue_id = ac.issue_id AND ie.mapped_canonical_state = 'DONE'
WHERE ac.project_id = $1
  AND ac.assignee_username = $2
GROUP BY ac.assignee_username, DATE_TRUNC('month', ie.event_timestamp)
ORDER BY month DESC
`

type GetUserPerformanceOverTimeParams struct {
	ProjectID        int32       `json:"project_id"`
	AssigneeUsername interface{} `json:"assignee_username"`
}

type GetUserPerformanceOverTimeRow struct {
	AssigneeUsername interface{}    `json:"assignee_username"`
	Month            pgtype.Date    `json:"month"`
	IssuesCompleted  int64          `json:"issues_completed"`
	TotalActiveHours pgtype.Numeric `json:"total_active_hours"`
	AvgActiveHours   pgtype.Numeric `json:"avg_active_hours"`
}

// Get user performance trends by month.
func (q *Queries) GetUserPerformanceOverTime(ctx context.Context, arg GetUserPerformanceOverTimeParams) ([]GetUserPerformanceOverTimeRow, error) {
	rows, err := q.db.Query(ctx, getUserPerformanceOverTime, arg.ProjectID, arg.AssigneeUsername)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserPerformanceOverTimeRow{}
	for rows.Next() {
		var i GetUserPerformanceOverTimeRow
		if err := rows.Scan(
			&i.AssigneeUsername,
			&i.Month,
			&i.IssuesCompleted,
			&i.TotalActiveHours,
			&i.AvgActiveHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
