// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dead_letter_queue.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUnresolvedDLQ = `-- name: CountUnresolvedDLQ :one
SELECT COUNT(*) FROM dead_letter_queue WHERE resolved = FALSE
`

func (q *Queries) CountUnresolvedDLQ(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnresolvedDLQ)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const incrementDLQRetry = `-- name: IncrementDLQRetry :exec
UPDATE dead_letter_queue
SET retry_count = retry_count + 1, last_retry_at = NOW()
WHERE id = $1
`

// Incrementa retry_count e atualiza last_retry_at.
func (q *Queries) IncrementDLQRetry(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementDLQRetry, id)
	return err
}

const insertDLQEntry = `-- name: InsertDLQEntry :one

INSERT INTO dead_letter_queue (project_id, issue_iid, event_type, raw_payload, error_message, error_category)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, issue_iid, event_type, raw_payload, error_message, error_category, retry_count, max_retries, last_retry_at, resolved, created_at
`

type InsertDLQEntryParams struct {
	ProjectID     int32       `json:"project_id"`
	IssueIid      pgtype.Int4 `json:"issue_iid"`
	EventType     pgtype.Text `json:"event_type"`
	RawPayload    []byte      `json:"raw_payload"`
	ErrorMessage  string      `json:"error_message"`
	ErrorCategory string      `json:"error_category"`
}

// db/query/dead_letter_queue.sql
// Insere um evento que falhou apos max retries.
func (q *Queries) InsertDLQEntry(ctx context.Context, arg InsertDLQEntryParams) (DeadLetterQueue, error) {
	row := q.db.QueryRow(ctx, insertDLQEntry,
		arg.ProjectID,
		arg.IssueIid,
		arg.EventType,
		arg.RawPayload,
		arg.ErrorMessage,
		arg.ErrorCategory,
	)
	var i DeadLetterQueue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.IssueIid,
		&i.EventType,
		&i.RawPayload,
		&i.ErrorMessage,
		&i.ErrorCategory,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastRetryAt,
		&i.Resolved,
		&i.CreatedAt,
	)
	return i, err
}

const listDLQByProject = `-- name: ListDLQByProject :many
SELECT id, project_id, issue_iid, event_type, raw_payload, error_message, error_category, retry_count, max_retries, last_retry_at, resolved, created_at FROM dead_letter_queue
WHERE project_id = $1 AND resolved = FALSE
ORDER BY created_at ASC
`

func (q *Queries) ListDLQByProject(ctx context.Context, projectID int32) ([]DeadLetterQueue, error) {
	rows, err := q.db.Query(ctx, listDLQByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterQueue{}
	for rows.Next() {
		var i DeadLetterQueue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueIid,
			&i.EventType,
			&i.RawPayload,
			&i.ErrorMessage,
			&i.ErrorCategory,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastRetryAt,
			&i.Resolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedDLQ = `-- name: ListUnresolvedDLQ :many
SELECT id, project_id, issue_iid, event_type, raw_payload, error_message, error_category, retry_count, max_retries, last_retry_at, resolved, created_at FROM dead_letter_queue
WHERE resolved = FALSE
ORDER BY created_at ASC
LIMIT $1
`

// Lista entradas DLQ nao resolvidas, mais antigas primeiro.
func (q *Queries) ListUnresolvedDLQ(ctx context.Context, limit int32) ([]DeadLetterQueue, error) {
	rows, err := q.db.Query(ctx, listUnresolvedDLQ, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterQueue{}
	for rows.Next() {
		var i DeadLetterQueue
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.IssueIid,
			&i.EventType,
			&i.RawPayload,
			&i.ErrorMessage,
			&i.ErrorCategory,
			&i.RetryCount,
			&i.MaxRetries,
			&i.LastRetryAt,
			&i.Resolved,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDLQResolved = `-- name: MarkDLQResolved :exec
UPDATE dead_letter_queue SET resolved = TRUE WHERE id = $1
`

func (q *Queries) MarkDLQResolved(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markDLQResolved, id)
	return err
}
