// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issues.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIssueByGitlabID = `-- name: GetIssueByGitlabID :one
SELECT id, gitlab_issue_id, project_id, iid, title, current_canonical_state, metadata_labels, assignees, gitlab_created_at, created_at, updated_at FROM issues WHERE gitlab_issue_id = $1
`

func (q *Queries) GetIssueByGitlabID(ctx context.Context, gitlabIssueID int32) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByGitlabID, gitlabIssueID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.CurrentCanonicalState,
		&i.MetadataLabels,
		&i.Assignees,
		&i.GitlabCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT id, gitlab_issue_id, project_id, iid, title, current_canonical_state, metadata_labels, assignees, gitlab_created_at, created_at, updated_at FROM issues WHERE id = $1
`

func (q *Queries) GetIssueByID(ctx context.Context, id int32) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.CurrentCanonicalState,
		&i.MetadataLabels,
		&i.Assignees,
		&i.GitlabCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssueByProjectAndIID = `-- name: GetIssueByProjectAndIID :one
SELECT id, gitlab_issue_id, project_id, iid, title, current_canonical_state, metadata_labels, assignees, gitlab_created_at, created_at, updated_at FROM issues WHERE project_id = $1 AND iid = $2
`

type GetIssueByProjectAndIIDParams struct {
	ProjectID int32 `json:"project_id"`
	Iid       int32 `json:"iid"`
}

func (q *Queries) GetIssueByProjectAndIID(ctx context.Context, arg GetIssueByProjectAndIIDParams) (Issue, error) {
	row := q.db.QueryRow(ctx, getIssueByProjectAndIID, arg.ProjectID, arg.Iid)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.CurrentCanonicalState,
		&i.MetadataLabels,
		&i.Assignees,
		&i.GitlabCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssuesByProject = `-- name: ListIssuesByProject :many
SELECT id, gitlab_issue_id, project_id, iid, title, current_canonical_state, metadata_labels, assignees, gitlab_created_at, created_at, updated_at FROM issues WHERE project_id = $1 ORDER BY iid
`

func (q *Queries) ListIssuesByProject(ctx context.Context, projectID int32) ([]Issue, error) {
	rows, err := q.db.Query(ctx, listIssuesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Issue{}
	for rows.Next() {
		var i Issue
		if err := rows.Scan(
			&i.ID,
			&i.GitlabIssueID,
			&i.ProjectID,
			&i.Iid,
			&i.Title,
			&i.CurrentCanonicalState,
			&i.MetadataLabels,
			&i.Assignees,
			&i.GitlabCreatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueAssignees = `-- name: UpdateIssueAssignees :exec
UPDATE issues SET 
    assignees = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateIssueAssigneesParams struct {
	Assignees []byte `json:"assignees"`
	ID        int32  `json:"id"`
}

// Atualiza o histórico de assignees da issue.
func (q *Queries) UpdateIssueAssignees(ctx context.Context, arg UpdateIssueAssigneesParams) error {
	_, err := q.db.Exec(ctx, updateIssueAssignees, arg.Assignees, arg.ID)
	return err
}

const updateIssueCanonicalState = `-- name: UpdateIssueCanonicalState :exec
UPDATE issues SET current_canonical_state = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateIssueCanonicalStateParams struct {
	CurrentCanonicalState pgtype.Text `json:"current_canonical_state"`
	ID                    int32       `json:"id"`
}

// Atualiza o cache de estado canonico da issue.
func (q *Queries) UpdateIssueCanonicalState(ctx context.Context, arg UpdateIssueCanonicalStateParams) error {
	_, err := q.db.Exec(ctx, updateIssueCanonicalState, arg.CurrentCanonicalState, arg.ID)
	return err
}

const updateIssueMetadata = `-- name: UpdateIssueMetadata :exec
UPDATE issues SET 
    metadata_labels = $1,
    updated_at = NOW()
WHERE id = $2
`

type UpdateIssueMetadataParams struct {
	MetadataLabels []byte `json:"metadata_labels"`
	ID             int32  `json:"id"`
}

func (q *Queries) UpdateIssueMetadata(ctx context.Context, arg UpdateIssueMetadataParams) error {
	_, err := q.db.Exec(ctx, updateIssueMetadata, arg.MetadataLabels, arg.ID)
	return err
}

const upsertIssue = `-- name: UpsertIssue :one
INSERT INTO issues (
    gitlab_issue_id, project_id, iid, title,
    current_canonical_state, metadata_labels, assignees,
    gitlab_created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW())
ON CONFLICT (project_id, iid) DO UPDATE SET
    gitlab_issue_id = EXCLUDED.gitlab_issue_id,
    title = EXCLUDED.title,
    current_canonical_state = EXCLUDED.current_canonical_state,
    metadata_labels = EXCLUDED.metadata_labels,
    assignees = EXCLUDED.assignees,
    updated_at = NOW()
RETURNING id, gitlab_issue_id, project_id, iid, title, current_canonical_state, metadata_labels, assignees, gitlab_created_at, created_at, updated_at
`

type UpsertIssueParams struct {
	GitlabIssueID         int32              `json:"gitlab_issue_id"`
	ProjectID             int32              `json:"project_id"`
	Iid                   int32              `json:"iid"`
	Title                 pgtype.Text        `json:"title"`
	CurrentCanonicalState pgtype.Text        `json:"current_canonical_state"`
	MetadataLabels        []byte             `json:"metadata_labels"`
	Assignees             []byte             `json:"assignees"`
	GitlabCreatedAt       pgtype.Timestamptz `json:"gitlab_created_at"`
}

// Insere ou atualiza uma issue na camada Silver.
func (q *Queries) UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, upsertIssue,
		arg.GitlabIssueID,
		arg.ProjectID,
		arg.Iid,
		arg.Title,
		arg.CurrentCanonicalState,
		arg.MetadataLabels,
		arg.Assignees,
		arg.GitlabCreatedAt,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.CurrentCanonicalState,
		&i.MetadataLabels,
		&i.Assignees,
		&i.GitlabCreatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
