// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countIssueEventsByProject = `-- name: CountIssueEventsByProject :one
SELECT COUNT(*) FROM issue_events WHERE project_id = $1
`

func (q *Queries) CountIssueEventsByProject(ctx context.Context, projectID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countIssueEventsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastIssueEvent = `-- name: GetLastIssueEvent :one
SELECT id, gitlab_event_id, issue_id, project_id, issue_iid, author_name, raw_label_added, raw_label_removed, mapped_canonical_state, event_timestamp, is_noise, cycle_count, created_at FROM issue_events
WHERE issue_id = $1 AND is_noise = FALSE
ORDER BY event_timestamp DESC
LIMIT 1
`

// Returns the most recent non-noise event for an issue (for edge case detection).
func (q *Queries) GetLastIssueEvent(ctx context.Context, issueID int32) (IssueEvent, error) {
	row := q.db.QueryRow(ctx, getLastIssueEvent, issueID)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.GitlabEventID,
		&i.IssueID,
		&i.ProjectID,
		&i.IssueIid,
		&i.AuthorName,
		&i.RawLabelAdded,
		&i.RawLabelRemoved,
		&i.MappedCanonicalState,
		&i.EventTimestamp,
		&i.IsNoise,
		&i.CycleCount,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestIssueEvent = `-- name: GetLatestIssueEvent :one
SELECT id, gitlab_event_id, issue_id, project_id, issue_iid, author_name, raw_label_added, raw_label_removed, mapped_canonical_state, event_timestamp, is_noise, cycle_count, created_at FROM issue_events
WHERE issue_id = $1 AND is_noise = FALSE
ORDER BY event_timestamp DESC
LIMIT 1
`

// Retorna o evento mais recente de uma issue (para calcular estado atual).
func (q *Queries) GetLatestIssueEvent(ctx context.Context, issueID int32) (IssueEvent, error) {
	row := q.db.QueryRow(ctx, getLatestIssueEvent, issueID)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.GitlabEventID,
		&i.IssueID,
		&i.ProjectID,
		&i.IssueIid,
		&i.AuthorName,
		&i.RawLabelAdded,
		&i.RawLabelRemoved,
		&i.MappedCanonicalState,
		&i.EventTimestamp,
		&i.IsNoise,
		&i.CycleCount,
		&i.CreatedAt,
	)
	return i, err
}

const insertIssueEvent = `-- name: InsertIssueEvent :one
INSERT INTO issue_events (
    gitlab_event_id, issue_id, project_id, issue_iid,
    author_name, raw_label_added, raw_label_removed,
    mapped_canonical_state, event_timestamp, is_noise, cycle_count
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (gitlab_event_id, project_id) DO NOTHING
RETURNING id, gitlab_event_id, issue_id, project_id, issue_iid, author_name, raw_label_added, raw_label_removed, mapped_canonical_state, event_timestamp, is_noise, cycle_count, created_at
`

type InsertIssueEventParams struct {
	GitlabEventID        pgtype.Int8        `json:"gitlab_event_id"`
	IssueID              int32              `json:"issue_id"`
	ProjectID            int32              `json:"project_id"`
	IssueIid             int32              `json:"issue_iid"`
	AuthorName           pgtype.Text        `json:"author_name"`
	RawLabelAdded        pgtype.Text        `json:"raw_label_added"`
	RawLabelRemoved      pgtype.Text        `json:"raw_label_removed"`
	MappedCanonicalState string             `json:"mapped_canonical_state"`
	EventTimestamp       pgtype.Timestamptz `json:"event_timestamp"`
	IsNoise              bool               `json:"is_noise"`
	CycleCount           pgtype.Int4        `json:"cycle_count"`
}

// Insere um evento normalizado na camada Silver.
func (q *Queries) InsertIssueEvent(ctx context.Context, arg InsertIssueEventParams) (IssueEvent, error) {
	row := q.db.QueryRow(ctx, insertIssueEvent,
		arg.GitlabEventID,
		arg.IssueID,
		arg.ProjectID,
		arg.IssueIid,
		arg.AuthorName,
		arg.RawLabelAdded,
		arg.RawLabelRemoved,
		arg.MappedCanonicalState,
		arg.EventTimestamp,
		arg.IsNoise,
		arg.CycleCount,
	)
	var i IssueEvent
	err := row.Scan(
		&i.ID,
		&i.GitlabEventID,
		&i.IssueID,
		&i.ProjectID,
		&i.IssueIid,
		&i.AuthorName,
		&i.RawLabelAdded,
		&i.RawLabelRemoved,
		&i.MappedCanonicalState,
		&i.EventTimestamp,
		&i.IsNoise,
		&i.CycleCount,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueEventsByIssue = `-- name: ListIssueEventsByIssue :many
SELECT id, gitlab_event_id, issue_id, project_id, issue_iid, author_name, raw_label_added, raw_label_removed, mapped_canonical_state, event_timestamp, is_noise, cycle_count, created_at FROM issue_events
WHERE issue_id = $1
ORDER BY event_timestamp ASC
`

// Lista eventos de uma issue especifica, ordenados por timestamp.
func (q *Queries) ListIssueEventsByIssue(ctx context.Context, issueID int32) ([]IssueEvent, error) {
	rows, err := q.db.Query(ctx, listIssueEventsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueEvent{}
	for rows.Next() {
		var i IssueEvent
		if err := rows.Scan(
			&i.ID,
			&i.GitlabEventID,
			&i.IssueID,
			&i.ProjectID,
			&i.IssueIid,
			&i.AuthorName,
			&i.RawLabelAdded,
			&i.RawLabelRemoved,
			&i.MappedCanonicalState,
			&i.EventTimestamp,
			&i.IsNoise,
			&i.CycleCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueEventsByProject = `-- name: ListIssueEventsByProject :many
SELECT id, gitlab_event_id, issue_id, project_id, issue_iid, author_name, raw_label_added, raw_label_removed, mapped_canonical_state, event_timestamp, is_noise, cycle_count, created_at FROM issue_events
WHERE project_id = $1
ORDER BY event_timestamp ASC
`

// Lista eventos de um projeto, ordenados por timestamp.
func (q *Queries) ListIssueEventsByProject(ctx context.Context, projectID int32) ([]IssueEvent, error) {
	rows, err := q.db.Query(ctx, listIssueEventsByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueEvent{}
	for rows.Next() {
		var i IssueEvent
		if err := rows.Scan(
			&i.ID,
			&i.GitlabEventID,
			&i.IssueID,
			&i.ProjectID,
			&i.IssueIid,
			&i.AuthorName,
			&i.RawLabelAdded,
			&i.RawLabelRemoved,
			&i.MappedCanonicalState,
			&i.EventTimestamp,
			&i.IsNoise,
			&i.CycleCount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
