// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: issue_comments.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertIssueComment = `-- name: InsertIssueComment :one
INSERT INTO issue_comments (
    gitlab_note_id, issue_id, author_name, body, comment_timestamp
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (gitlab_note_id) DO NOTHING
RETURNING id, gitlab_note_id, issue_id, author_name, body, comment_timestamp, created_at
`

type InsertIssueCommentParams struct {
	GitlabNoteID     int64              `json:"gitlab_note_id"`
	IssueID          int32              `json:"issue_id"`
	AuthorName       pgtype.Text        `json:"author_name"`
	Body             pgtype.Text        `json:"body"`
	CommentTimestamp pgtype.Timestamptz `json:"comment_timestamp"`
}

// Insere um comentario normalizado na camada Silver.
func (q *Queries) InsertIssueComment(ctx context.Context, arg InsertIssueCommentParams) (IssueComment, error) {
	row := q.db.QueryRow(ctx, insertIssueComment,
		arg.GitlabNoteID,
		arg.IssueID,
		arg.AuthorName,
		arg.Body,
		arg.CommentTimestamp,
	)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.GitlabNoteID,
		&i.IssueID,
		&i.AuthorName,
		&i.Body,
		&i.CommentTimestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueCommentsByIssue = `-- name: ListIssueCommentsByIssue :many
SELECT id, gitlab_note_id, issue_id, author_name, body, comment_timestamp, created_at FROM issue_comments
WHERE issue_id = $1
ORDER BY comment_timestamp ASC
`

func (q *Queries) ListIssueCommentsByIssue(ctx context.Context, issueID int32) ([]IssueComment, error) {
	rows, err := q.db.Query(ctx, listIssueCommentsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IssueComment{}
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.GitlabNoteID,
			&i.IssueID,
			&i.AuthorName,
			&i.Body,
			&i.CommentTimestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
