// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metadata_mapping.sql

package repository

import (
	"context"
)

const getMetadataMappingByLabel = `-- name: GetMetadataMappingByLabel :one
SELECT id, gitlab_label_name, metadata_key, created_at FROM metadata_mapping WHERE gitlab_label_name = $1
`

func (q *Queries) GetMetadataMappingByLabel(ctx context.Context, gitlabLabelName string) (MetadataMapping, error) {
	row := q.db.QueryRow(ctx, getMetadataMappingByLabel, gitlabLabelName)
	var i MetadataMapping
	err := row.Scan(
		&i.ID,
		&i.GitlabLabelName,
		&i.MetadataKey,
		&i.CreatedAt,
	)
	return i, err
}

const listMetadataMappings = `-- name: ListMetadataMappings :many
SELECT id, gitlab_label_name, metadata_key, created_at FROM metadata_mapping ORDER BY metadata_key, gitlab_label_name
`

// Lista todos os mapeamentos de metadados. Usado pelo StateMapper no startup.
func (q *Queries) ListMetadataMappings(ctx context.Context) ([]MetadataMapping, error) {
	rows, err := q.db.Query(ctx, listMetadataMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MetadataMapping{}
	for rows.Next() {
		var i MetadataMapping
		if err := rows.Scan(
			&i.ID,
			&i.GitlabLabelName,
			&i.MetadataKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMetadataMapping = `-- name: UpsertMetadataMapping :one
INSERT INTO metadata_mapping (gitlab_label_name, metadata_key)
VALUES ($1, $2)
ON CONFLICT (gitlab_label_name) DO UPDATE SET
    metadata_key = EXCLUDED.metadata_key
RETURNING id, gitlab_label_name, metadata_key, created_at
`

type UpsertMetadataMappingParams struct {
	GitlabLabelName string `json:"gitlab_label_name"`
	MetadataKey     string `json:"metadata_key"`
}

func (q *Queries) UpsertMetadataMapping(ctx context.Context, arg UpsertMetadataMappingParams) (MetadataMapping, error) {
	row := q.db.QueryRow(ctx, upsertMetadataMapping, arg.GitlabLabelName, arg.MetadataKey)
	var i MetadataMapping
	err := row.Scan(
		&i.ID,
		&i.GitlabLabelName,
		&i.MetadataKey,
		&i.CreatedAt,
	)
	return i, err
}
