// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeadLetterQueue struct {
	ID            int64              `json:"id"`
	ProjectID     int32              `json:"project_id"`
	IssueIid      pgtype.Int4        `json:"issue_iid"`
	EventType     pgtype.Text        `json:"event_type"`
	RawPayload    []byte             `json:"raw_payload"`
	ErrorMessage  string             `json:"error_message"`
	ErrorCategory string             `json:"error_category"`
	RetryCount    int32              `json:"retry_count"`
	MaxRetries    int32              `json:"max_retries"`
	LastRetryAt   pgtype.Timestamptz `json:"last_retry_at"`
	Resolved      bool               `json:"resolved"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

// Silver Layer: Issues normalizadas com estados canônicos mapeados e metadados estruturados.
type Issue struct {
	ID            int32       `json:"id"`
	GitlabIssueID int32       `json:"gitlab_issue_id"`
	ProjectID     int32       `json:"project_id"`
	Iid           int32       `json:"iid"`
	Title         pgtype.Text `json:"title"`
	// Cache do último estado canônico processado (BACKLOG, IN_PROGRESS, etc.).
	CurrentCanonicalState pgtype.Text `json:"current_canonical_state"`
	// Array de labels categóricas (não-estado) como Bug, Correção, etc.
	MetadataLabels  []byte             `json:"metadata_labels"`
	Assignees       []byte             `json:"assignees"`
	GitlabCreatedAt pgtype.Timestamptz `json:"gitlab_created_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Silver Layer: Comentários de issues estruturados e normalizados.
type IssueComment struct {
	ID               int64              `json:"id"`
	GitlabNoteID     int64              `json:"gitlab_note_id"`
	IssueID          int32              `json:"issue_id"`
	AuthorName       pgtype.Text        `json:"author_name"`
	Body             pgtype.Text        `json:"body"`
	CommentTimestamp pgtype.Timestamptz `json:"comment_timestamp"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Silver Layer: Eventos de issues normalizados com estados canônicos mapeados. Dados limpos e estruturados.
type IssueEvent struct {
	ID              int64       `json:"id"`
	GitlabEventID   pgtype.Int8 `json:"gitlab_event_id"`
	IssueID         int32       `json:"issue_id"`
	ProjectID       int32       `json:"project_id"`
	IssueIid        int32       `json:"issue_iid"`
	AuthorName      pgtype.Text `json:"author_name"`
	RawLabelAdded   pgtype.Text `json:"raw_label_added"`
	RawLabelRemoved pgtype.Text `json:"raw_label_removed"`
	// Estado canônico mapeado (BACKLOG, IN_PROGRESS, QA_REVIEW, BLOCKED, DONE, CANCELED, UNKNOWN).
	MappedCanonicalState string             `json:"mapped_canonical_state"`
	EventTimestamp       pgtype.Timestamptz `json:"event_timestamp"`
	// Flag indicando evento de "dedo nervoso" (transição < 15min) para ser ignorado em métricas.
	IsNoise bool `json:"is_noise"`
	// Número de ciclos de retrabalho (transições QA_REVIEW → IN_PROGRESS).
	CycleCount pgtype.Int4        `json:"cycle_count"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// Config Layer: Mapeamento de labels que representam metadados (não-estados) como tipo, prioridade, etc.
type MetadataMapping struct {
	ID              int32  `json:"id"`
	GitlabLabelName string `json:"gitlab_label_name"`
	// Chave categórica: tipo, prioridade, severidade, etc.
	MetadataKey string             `json:"metadata_key"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Silver Layer: Projetos normalizados e estruturados, prontos para análise.
type Project struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Bronze Layer: Eventos brutos do GitLab preservados exatamente como recebidos da API. Imutável e append-only.
type RawEvent struct {
	ID            int64       `json:"id"`
	GitlabEventID pgtype.Int8 `json:"gitlab_event_id"`
	ProjectID     int32       `json:"project_id"`
	IssueIid      int32       `json:"issue_iid"`
	EventType     string      `json:"event_type"`
	// Payload completo da API GitLab (resource_label_events, notes, etc.) preservado em JSONB.
	RawPayload []byte             `json:"raw_payload"`
	FetchedAt  pgtype.Timestamptz `json:"fetched_at"`
	// Flag indicando se o evento já foi transformado para a camada Silver.
	Processed bool               `json:"processed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Bronze Layer: Raw issue metadata from GitLab API
type RawIssue struct {
	ID            int64       `json:"id"`
	GitlabIssueID int64       `json:"gitlab_issue_id"`
	ProjectID     int32       `json:"project_id"`
	Iid           int32       `json:"iid"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	State         string      `json:"state"`
	// Complete issue JSON payload from GitLab API
	RawPayload []byte             `json:"raw_payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// Bronze Layer: Cache de projetos do GitLab com metadados brutos preservados em JSONB.
type RawProject struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	// Payload completo retornado pela API GitLab para este projeto.
	RawMetadata []byte             `json:"raw_metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

// Config Layer: Mapeamento de labels do GitLab para estados canônicos.
type StateMapping struct {
	ID              int32  `json:"id"`
	GitlabLabelName string `json:"gitlab_label_name"`
	// Estado canônico: BACKLOG, IN_PROGRESS, QA_REVIEW, BLOCKED, DONE, CANCELED, UNKNOWN.
	CanonicalState string             `json:"canonical_state"`
	Description    pgtype.Text        `json:"description"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Controla o cursor de sincronização incremental (updated_after) para cada projeto.
type SyncState struct {
	ID           int32              `json:"id"`
	ProjectID    int32              `json:"project_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Config Layer: Log de labels encontradas no GitLab que não estão mapeadas em state_mapping ou metadata_mapping.
type UnknownLabelsLog struct {
	ID        int32  `json:"id"`
	LabelName string `json:"label_name"`
	// Número de vezes que esta label não mapeada foi encontrada.
	OccurrenceCount int32              `json:"occurrence_count"`
	FirstSeenAt     pgtype.Timestamptz `json:"first_seen_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
}

// Metricas por issue: lead time, cycle time, blocked time, rework, ghost work e timestamps de ciclo.
type VwIssueLifecycleMetric struct {
	IssueID                     int32              `json:"issue_id"`
	ProjectID                   int32              `json:"project_id"`
	ProjectPath                 string             `json:"project_path"`
	IssueIid                    int32              `json:"issue_iid"`
	GitlabIssueID               int32              `json:"gitlab_issue_id"`
	IssueTitle                  pgtype.Text        `json:"issue_title"`
	CurrentCanonicalState       string             `json:"current_canonical_state"`
	CachedCurrentCanonicalState pgtype.Text        `json:"cached_current_canonical_state"`
	MetadataLabels              []byte             `json:"metadata_labels"`
	Assignees                   []byte             `json:"assignees"`
	GitlabCreatedAt             pgtype.Timestamptz `json:"gitlab_created_at"`
	LifecycleStartAt            interface{}        `json:"lifecycle_start_at"`
	LifecycleStartSource        string             `json:"lifecycle_start_source"`
	FirstBacklogAt              interface{}        `json:"first_backlog_at"`
	FirstInProgressAt           interface{}        `json:"first_in_progress_at"`
	FirstQaReviewAt             interface{}        `json:"first_qa_review_at"`
	FirstBlockedAt              interface{}        `json:"first_blocked_at"`
	FirstTouchAt                interface{}        `json:"first_touch_at"`
	FirstDoneAt                 interface{}        `json:"first_done_at"`
	FinalDoneAt                 interface{}        `json:"final_done_at"`
	IsCompleted                 pgtype.Bool        `json:"is_completed"`
	SkippedInProgressFlag       pgtype.Bool        `json:"skipped_in_progress_flag"`
	InProgressEntryCount        int64              `json:"in_progress_entry_count"`
	QaReviewEntryCount          int64              `json:"qa_review_entry_count"`
	BlockedEntryCount           int64              `json:"blocked_entry_count"`
	DoneEntryCount              int64              `json:"done_entry_count"`
	QaToDevReturnCount          int64              `json:"qa_to_dev_return_count"`
	ReopenedAfterDoneCount      int64              `json:"reopened_after_done_count"`
	MaxCycleCountRecorded       interface{}        `json:"max_cycle_count_recorded"`
	InProgressTimeHours         pgtype.Numeric     `json:"in_progress_time_hours"`
	QaReviewTimeHours           pgtype.Numeric     `json:"qa_review_time_hours"`
	CycleTimeHours              pgtype.Numeric     `json:"cycle_time_hours"`
	BlockedTimeHours            pgtype.Numeric     `json:"blocked_time_hours"`
	ElapsedLeadTimeHours        pgtype.Numeric     `json:"elapsed_lead_time_hours"`
	LeadTimeHours               interface{}        `json:"lead_time_hours"`
	BacklogWaitHours            interface{}        `json:"backlog_wait_hours"`
	FlowEfficiencyPct           interface{}        `json:"flow_efficiency_pct"`
}

// Intervalos por estado canonico com entered_at, exited_at e duracao em horas.
type VwIssueStateInterval struct {
	IssueEventID           int64              `json:"issue_event_id"`
	GitlabEventID          pgtype.Int8        `json:"gitlab_event_id"`
	IssueID                int32              `json:"issue_id"`
	ProjectID              int32              `json:"project_id"`
	ProjectPath            string             `json:"project_path"`
	IssueIid               int32              `json:"issue_iid"`
	GitlabIssueID          int32              `json:"gitlab_issue_id"`
	IssueTitle             pgtype.Text        `json:"issue_title"`
	GitlabCreatedAt        pgtype.Timestamptz `json:"gitlab_created_at"`
	CurrentCanonicalState  pgtype.Text        `json:"current_canonical_state"`
	TransitionSeq          int64              `json:"transition_seq"`
	PreviousCanonicalState interface{}        `json:"previous_canonical_state"`
	CanonicalState         string             `json:"canonical_state"`
	NextCanonicalState     interface{}        `json:"next_canonical_state"`
	EnteredAt              pgtype.Timestamptz `json:"entered_at"`
	ExitedAt               interface{}        `json:"exited_at"`
	IsOpenInterval         interface{}        `json:"is_open_interval"`
	DurationHours          pgtype.Numeric     `json:"duration_hours"`
	AuthorName             pgtype.Text        `json:"author_name"`
	RawLabelAdded          pgtype.Text        `json:"raw_label_added"`
	RawLabelRemoved        pgtype.Text        `json:"raw_label_removed"`
	CycleCount             pgtype.Int4        `json:"cycle_count"`
}

// Timeline limpo por issue, removendo ruido e estados canonicos consecutivos duplicados.
type VwIssueStateTransition struct {
	IssueEventID             int64              `json:"issue_event_id"`
	GitlabEventID            pgtype.Int8        `json:"gitlab_event_id"`
	IssueID                  int32              `json:"issue_id"`
	ProjectID                int32              `json:"project_id"`
	ProjectPath              string             `json:"project_path"`
	IssueIid                 int32              `json:"issue_iid"`
	GitlabIssueID            int32              `json:"gitlab_issue_id"`
	IssueTitle               pgtype.Text        `json:"issue_title"`
	GitlabCreatedAt          pgtype.Timestamptz `json:"gitlab_created_at"`
	CurrentCanonicalState    pgtype.Text        `json:"current_canonical_state"`
	TransitionSeq            int64              `json:"transition_seq"`
	PreviousCanonicalState   interface{}        `json:"previous_canonical_state"`
	CanonicalState           string             `json:"canonical_state"`
	NextCanonicalState       interface{}        `json:"next_canonical_state"`
	EnteredAt                pgtype.Timestamptz `json:"entered_at"`
	ExitedAt                 interface{}        `json:"exited_at"`
	DurationHoursToNextState pgtype.Numeric     `json:"duration_hours_to_next_state"`
	AuthorName               pgtype.Text        `json:"author_name"`
	RawLabelAdded            pgtype.Text        `json:"raw_label_added"`
	RawLabelRemoved          pgtype.Text        `json:"raw_label_removed"`
	CycleCount               pgtype.Int4        `json:"cycle_count"`
}

// Resumo por projeto com throughput, tempos medios, ghost work, retrabalho e bloqueios.
type VwProjectEngineeringMetric struct {
	ProjectID                int32          `json:"project_id"`
	ProjectPath              string         `json:"project_path"`
	TotalIssues              int64          `json:"total_issues"`
	CompletedIssues          int64          `json:"completed_issues"`
	OpenIssues               int64          `json:"open_issues"`
	BacklogIssues            int64          `json:"backlog_issues"`
	InProgressIssues         int64          `json:"in_progress_issues"`
	QaReviewIssues           int64          `json:"qa_review_issues"`
	BlockedIssues            int64          `json:"blocked_issues"`
	CanceledIssues           int64          `json:"canceled_issues"`
	CompletedLast30Days      int64          `json:"completed_last_30_days"`
	AvgLeadTimeHours         pgtype.Numeric `json:"avg_lead_time_hours"`
	P50LeadTimeHours         pgtype.Numeric `json:"p50_lead_time_hours"`
	AvgCycleTimeHours        pgtype.Numeric `json:"avg_cycle_time_hours"`
	P50CycleTimeHours        pgtype.Numeric `json:"p50_cycle_time_hours"`
	AvgBlockedTimeHours      pgtype.Numeric `json:"avg_blocked_time_hours"`
	AvgBacklogWaitHours      pgtype.Numeric `json:"avg_backlog_wait_hours"`
	AvgFlowEfficiencyPct     pgtype.Numeric `json:"avg_flow_efficiency_pct"`
	GhostWorkCompletedIssues int64          `json:"ghost_work_completed_issues"`
	GhostWorkPct             pgtype.Numeric `json:"ghost_work_pct"`
	ReworkIssues             int64          `json:"rework_issues"`
	AvgReworkCount           pgtype.Numeric `json:"avg_rework_count"`
	ReworkIssuePct           pgtype.Numeric `json:"rework_issue_pct"`
	BlockedIssuesWithTime    int64          `json:"blocked_issues_with_time"`
	BlockedIssuePct          pgtype.Numeric `json:"blocked_issue_pct"`
}

// Catalogo de projetos para APIs e seletores, com volumetria de issues e ultimo sync consolidado.
type VwProjectsCatalog struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	GroupPath    string             `json:"group_path"`
	TotalIssues  int64              `json:"total_issues"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
