// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProject = `-- name: GetProject :one
SELECT id, name, path, last_synced_at, created_at, updated_at FROM projects WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int32) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjects = `-- name: ListProjects :many
SELECT id, name, path, last_synced_at, created_at, updated_at FROM projects ORDER BY name
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const syncProjectLastSynced = `-- name: SyncProjectLastSynced :one
WITH matched_projects AS (
    SELECT p.id
    FROM projects p
    JOIN raw_projects rp ON rp.id = p.id
    WHERE p.id = $2
    FOR UPDATE
),
updated_project AS (
    UPDATE projects AS p
    SET last_synced_at = $1, updated_at = NOW()
    FROM matched_projects mp
    WHERE p.id = mp.id
    RETURNING p.id
),
updated_raw AS (
    UPDATE raw_projects AS rp
    SET last_synced_at = $1, updated_at = NOW()
    FROM matched_projects mp
    WHERE rp.id = mp.id
    RETURNING rp.id
)
SELECT
    (SELECT COUNT(*) FROM updated_raw) AS raw_projects_updated,
    (SELECT COUNT(*) FROM updated_project) AS projects_updated
`

type SyncProjectLastSyncedParams struct {
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	ID           int32              `json:"id"`
}

type SyncProjectLastSyncedRow struct {
	RawProjectsUpdated int64 `json:"raw_projects_updated"`
	ProjectsUpdated    int64 `json:"projects_updated"`
}

func (q *Queries) SyncProjectLastSynced(ctx context.Context, arg SyncProjectLastSyncedParams) (SyncProjectLastSyncedRow, error) {
	row := q.db.QueryRow(ctx, syncProjectLastSynced, arg.LastSyncedAt, arg.ID)
	var i SyncProjectLastSyncedRow
	err := row.Scan(&i.RawProjectsUpdated, &i.ProjectsUpdated)
	return i, err
}

const upsertProject = `-- name: UpsertProject :one
INSERT INTO projects (id, name, path, last_synced_at, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    last_synced_at = GREATEST(projects.last_synced_at, EXCLUDED.last_synced_at),
    updated_at = NOW()
RETURNING id, name, path, last_synced_at, created_at, updated_at
`

type UpsertProjectParams struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

// Insere ou atualiza um projeto na camada Silver.
// Usado pelo Transformer ao normalizar raw_projects -> projects.
func (q *Queries) UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, upsertProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.LastSyncedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
