// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: projects_catalog.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listProjectsCatalog = `-- name: ListProjectsCatalog :many
SELECT id, name, path, group_path, total_issues, last_synced_at
FROM vw_projects_catalog
ORDER BY name
`

type ListProjectsCatalogRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	GroupPath    string             `json:"group_path"`
	TotalIssues  int64              `json:"total_issues"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) ListProjectsCatalog(ctx context.Context) ([]ListProjectsCatalogRow, error) {
	rows, err := q.db.Query(ctx, listProjectsCatalog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectsCatalogRow{}
	for rows.Next() {
		var i ListProjectsCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.GroupPath,
			&i.TotalIssues,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProjectsCatalog = `-- name: SearchProjectsCatalog :many
SELECT id, name, path, group_path, total_issues, last_synced_at
FROM vw_projects_catalog
WHERE ($1::text = '' OR name ILIKE '%' || $1 || '%' OR path ILIKE '%' || $1 || '%')
  AND ($2::text = '' OR group_path = $2)
ORDER BY name
`

type SearchProjectsCatalogParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
}

type SearchProjectsCatalogRow struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	GroupPath    string             `json:"group_path"`
	TotalIssues  int64              `json:"total_issues"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) SearchProjectsCatalog(ctx context.Context, arg SearchProjectsCatalogParams) ([]SearchProjectsCatalogRow, error) {
	rows, err := q.db.Query(ctx, searchProjectsCatalog, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchProjectsCatalogRow{}
	for rows.Next() {
		var i SearchProjectsCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.GroupPath,
			&i.TotalIssues,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
