// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Insere evento bruto (usado em batch). ON CONFLICT ignora duplicatas.
	BulkInsertRawEvent(ctx context.Context, arg BulkInsertRawEventParams) error
	CountIssueEventsByProject(ctx context.Context, projectID int32) (int64, error)
	CountRawEventsByProject(ctx context.Context, projectID int32) (int64, error)
	CountUnknownLabels(ctx context.Context) (int64, error)
	CountUnprocessedRawEvents(ctx context.Context) (int64, error)
	CountUnresolvedDLQ(ctx context.Context) (int64, error)
	GetIssueByGitlabID(ctx context.Context, gitlabIssueID int32) (Issue, error)
	GetIssueByID(ctx context.Context, id int32) (Issue, error)
	GetIssueByProjectAndIID(ctx context.Context, arg GetIssueByProjectAndIIDParams) (Issue, error)
	// Returns the most recent non-noise event for an issue (for edge case detection).
	GetLastIssueEvent(ctx context.Context, issueID int32) (IssueEvent, error)
	// Retorna o evento mais recente de uma issue (para calcular estado atual).
	GetLatestIssueEvent(ctx context.Context, issueID int32) (IssueEvent, error)
	GetMetadataMappingByLabel(ctx context.Context, gitlabLabelName string) (MetadataMapping, error)
	GetProject(ctx context.Context, id int32) (Project, error)
	GetRawIssueByProjectAndIID(ctx context.Context, arg GetRawIssueByProjectAndIIDParams) (RawIssue, error)
	GetRawProject(ctx context.Context, id int32) (RawProject, error)
	GetStateMappingByLabel(ctx context.Context, gitlabLabelName string) (StateMapping, error)
	GetSyncState(ctx context.Context, projectID int32) (SyncState, error)
	// Incrementa retry_count e atualiza last_retry_at.
	IncrementDLQRetry(ctx context.Context, id int64) error
	// db/query/dead_letter_queue.sql
	// Insere um evento que falhou apos max retries.
	InsertDLQEntry(ctx context.Context, arg InsertDLQEntryParams) (DeadLetterQueue, error)
	// Insere um comentario normalizado na camada Silver.
	InsertIssueComment(ctx context.Context, arg InsertIssueCommentParams) (IssueComment, error)
	// Insere um evento normalizado na camada Silver.
	InsertIssueEvent(ctx context.Context, arg InsertIssueEventParams) (IssueEvent, error)
	// Insere um evento bruto na camada Bronze. Append-only, imutavel.
	InsertRawEvent(ctx context.Context, arg InsertRawEventParams) (RawEvent, error)
	ListDLQByProject(ctx context.Context, projectID int32) ([]DeadLetterQueue, error)
	ListIssueCommentsByIssue(ctx context.Context, issueID int32) ([]IssueComment, error)
	// Lista eventos de uma issue especifica, ordenados por timestamp.
	ListIssueEventsByIssue(ctx context.Context, issueID int32) ([]IssueEvent, error)
	// Lista eventos de um projeto, ordenados por timestamp.
	ListIssueEventsByProject(ctx context.Context, projectID int32) ([]IssueEvent, error)
	ListIssuesByProject(ctx context.Context, projectID int32) ([]Issue, error)
	// Lista todos os mapeamentos de metadados. Usado pelo StateMapper no startup.
	ListMetadataMappings(ctx context.Context) ([]MetadataMapping, error)
	ListProjects(ctx context.Context) ([]Project, error)
	ListProjectsCatalog(ctx context.Context) ([]ListProjectsCatalogRow, error)
	ListRawIssuesByProject(ctx context.Context, projectID int32) ([]RawIssue, error)
	// Lista todos os projetos Bronze, ordenados por nome.
	ListRawProjects(ctx context.Context) ([]RawProject, error)
	// Lista projetos que precisam de sync (last_synced_at antes do threshold).
	ListRawProjectsDueSync(ctx context.Context, lastSyncedAt pgtype.Timestamptz) ([]RawProject, error)
	// Lista todos os mapeamentos de estado. Usado pelo StateMapper no startup.
	ListStateMappings(ctx context.Context) ([]StateMapping, error)
	// Lista labels desconhecidas ordenadas por frequencia (mais comuns primeiro).
	ListUnknownLabels(ctx context.Context) ([]UnknownLabelsLog, error)
	// Lista eventos Bronze ainda nao transformados para Silver.
	// Usado pelo Transformer para processar em batch.
	ListUnprocessedRawEvents(ctx context.Context, limit int32) ([]RawEvent, error)
	// Lista eventos nao processados de um projeto especifico.
	ListUnprocessedRawEventsByProject(ctx context.Context, arg ListUnprocessedRawEventsByProjectParams) ([]RawEvent, error)
	// Lista entradas DLQ nao resolvidas, mais antigas primeiro.
	ListUnresolvedDLQ(ctx context.Context, limit int32) ([]DeadLetterQueue, error)
	MarkDLQResolved(ctx context.Context, id int64) error
	// Marca evento como processado apos transformacao Silver.
	MarkRawEventProcessed(ctx context.Context, id int64) error
	// Marca multiplos eventos como processados.
	MarkRawEventsProcessedBatch(ctx context.Context, dollar_1 []int64) error
	SearchProjectsCatalog(ctx context.Context, arg SearchProjectsCatalogParams) ([]SearchProjectsCatalogRow, error)
	SyncProjectLastSynced(ctx context.Context, arg SyncProjectLastSyncedParams) (SyncProjectLastSyncedRow, error)
	// Atualiza o histórico de assignees da issue.
	UpdateIssueAssignees(ctx context.Context, arg UpdateIssueAssigneesParams) error
	// Atualiza o cache de estado canonico da issue.
	UpdateIssueCanonicalState(ctx context.Context, arg UpdateIssueCanonicalStateParams) error
	UpdateIssueMetadata(ctx context.Context, arg UpdateIssueMetadataParams) error
	// Atualiza o cursor de sincronizacao apos extração Bronze bem-sucedida.
	UpdateRawProjectLastSynced(ctx context.Context, arg UpdateRawProjectLastSyncedParams) error
	// Insere ou atualiza uma issue na camada Silver.
	UpsertIssue(ctx context.Context, arg UpsertIssueParams) (Issue, error)
	UpsertMetadataMapping(ctx context.Context, arg UpsertMetadataMappingParams) (MetadataMapping, error)
	// Insere ou atualiza um projeto na camada Silver.
	// Usado pelo Transformer ao normalizar raw_projects -> projects.
	UpsertProject(ctx context.Context, arg UpsertProjectParams) (Project, error)
	UpsertRawIssue(ctx context.Context, arg UpsertRawIssueParams) (RawIssue, error)
	// Insere ou atualiza um projeto na camada Bronze.
	// Usado pelo Discovery Service ao descobrir projetos novos.
	UpsertRawProject(ctx context.Context, arg UpsertRawProjectParams) (RawProject, error)
	UpsertStateMapping(ctx context.Context, arg UpsertStateMappingParams) (StateMapping, error)
	UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error)
	// Registra ou incrementa contagem de uma label desconhecida.
	UpsertUnknownLabel(ctx context.Context, labelName string) (UnknownLabelsLog, error)
}

var _ Querier = (*Queries)(nil)
