// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_issues.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawIssueByProjectAndIID = `-- name: GetRawIssueByProjectAndIID :one
SELECT id, gitlab_issue_id, project_id, iid, title, description, state, raw_payload, created_at, updated_at FROM raw_issues WHERE project_id = $1 AND iid = $2
`

type GetRawIssueByProjectAndIIDParams struct {
	ProjectID int32 `json:"project_id"`
	Iid       int32 `json:"iid"`
}

func (q *Queries) GetRawIssueByProjectAndIID(ctx context.Context, arg GetRawIssueByProjectAndIIDParams) (RawIssue, error) {
	row := q.db.QueryRow(ctx, getRawIssueByProjectAndIID, arg.ProjectID, arg.Iid)
	var i RawIssue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.Description,
		&i.State,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRawIssuesByProject = `-- name: ListRawIssuesByProject :many
SELECT id, gitlab_issue_id, project_id, iid, title, description, state, raw_payload, created_at, updated_at FROM raw_issues WHERE project_id = $1 ORDER BY iid
`

func (q *Queries) ListRawIssuesByProject(ctx context.Context, projectID int32) ([]RawIssue, error) {
	rows, err := q.db.Query(ctx, listRawIssuesByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawIssue{}
	for rows.Next() {
		var i RawIssue
		if err := rows.Scan(
			&i.ID,
			&i.GitlabIssueID,
			&i.ProjectID,
			&i.Iid,
			&i.Title,
			&i.Description,
			&i.State,
			&i.RawPayload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRawIssue = `-- name: UpsertRawIssue :one
INSERT INTO raw_issues (gitlab_issue_id, project_id, iid, title, description, state, raw_payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (project_id, iid) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    state = EXCLUDED.state,
    raw_payload = EXCLUDED.raw_payload,
    updated_at = NOW()
RETURNING id, gitlab_issue_id, project_id, iid, title, description, state, raw_payload, created_at, updated_at
`

type UpsertRawIssueParams struct {
	GitlabIssueID int64       `json:"gitlab_issue_id"`
	ProjectID     int32       `json:"project_id"`
	Iid           int32       `json:"iid"`
	Title         string      `json:"title"`
	Description   pgtype.Text `json:"description"`
	State         string      `json:"state"`
	RawPayload    []byte      `json:"raw_payload"`
}

func (q *Queries) UpsertRawIssue(ctx context.Context, arg UpsertRawIssueParams) (RawIssue, error) {
	row := q.db.QueryRow(ctx, upsertRawIssue,
		arg.GitlabIssueID,
		arg.ProjectID,
		arg.Iid,
		arg.Title,
		arg.Description,
		arg.State,
		arg.RawPayload,
	)
	var i RawIssue
	err := row.Scan(
		&i.ID,
		&i.GitlabIssueID,
		&i.ProjectID,
		&i.Iid,
		&i.Title,
		&i.Description,
		&i.State,
		&i.RawPayload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
