// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_events.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkInsertRawEvent = `-- name: BulkInsertRawEvent :exec
INSERT INTO raw_events (gitlab_event_id, project_id, issue_iid, event_type, raw_payload)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
`

type BulkInsertRawEventParams struct {
	GitlabEventID pgtype.Int8 `json:"gitlab_event_id"`
	ProjectID     int32       `json:"project_id"`
	IssueIid      int32       `json:"issue_iid"`
	EventType     string      `json:"event_type"`
	RawPayload    []byte      `json:"raw_payload"`
}

// Insere evento bruto (usado em batch). ON CONFLICT ignora duplicatas.
func (q *Queries) BulkInsertRawEvent(ctx context.Context, arg BulkInsertRawEventParams) error {
	_, err := q.db.Exec(ctx, bulkInsertRawEvent,
		arg.GitlabEventID,
		arg.ProjectID,
		arg.IssueIid,
		arg.EventType,
		arg.RawPayload,
	)
	return err
}

const countRawEventsByProject = `-- name: CountRawEventsByProject :one
SELECT COUNT(*) FROM raw_events WHERE project_id = $1
`

func (q *Queries) CountRawEventsByProject(ctx context.Context, projectID int32) (int64, error) {
	row := q.db.QueryRow(ctx, countRawEventsByProject, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnprocessedRawEvents = `-- name: CountUnprocessedRawEvents :one
SELECT COUNT(*) FROM raw_events WHERE processed = FALSE
`

func (q *Queries) CountUnprocessedRawEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnprocessedRawEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertRawEvent = `-- name: InsertRawEvent :one
INSERT INTO raw_events (gitlab_event_id, project_id, issue_iid, event_type, raw_payload)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, gitlab_event_id, project_id, issue_iid, event_type, raw_payload, fetched_at, processed, created_at
`

type InsertRawEventParams struct {
	GitlabEventID pgtype.Int8 `json:"gitlab_event_id"`
	ProjectID     int32       `json:"project_id"`
	IssueIid      int32       `json:"issue_iid"`
	EventType     string      `json:"event_type"`
	RawPayload    []byte      `json:"raw_payload"`
}

// Insere um evento bruto na camada Bronze. Append-only, imutavel.
func (q *Queries) InsertRawEvent(ctx context.Context, arg InsertRawEventParams) (RawEvent, error) {
	row := q.db.QueryRow(ctx, insertRawEvent,
		arg.GitlabEventID,
		arg.ProjectID,
		arg.IssueIid,
		arg.EventType,
		arg.RawPayload,
	)
	var i RawEvent
	err := row.Scan(
		&i.ID,
		&i.GitlabEventID,
		&i.ProjectID,
		&i.IssueIid,
		&i.EventType,
		&i.RawPayload,
		&i.FetchedAt,
		&i.Processed,
		&i.CreatedAt,
	)
	return i, err
}

const listUnprocessedRawEvents = `-- name: ListUnprocessedRawEvents :many
SELECT id, gitlab_event_id, project_id, issue_iid, event_type, raw_payload, fetched_at, processed, created_at FROM raw_events
WHERE processed = FALSE
ORDER BY fetched_at ASC
LIMIT $1
`

// Lista eventos Bronze ainda nao transformados para Silver.
// Usado pelo Transformer para processar em batch.
func (q *Queries) ListUnprocessedRawEvents(ctx context.Context, limit int32) ([]RawEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedRawEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawEvent{}
	for rows.Next() {
		var i RawEvent
		if err := rows.Scan(
			&i.ID,
			&i.GitlabEventID,
			&i.ProjectID,
			&i.IssueIid,
			&i.EventType,
			&i.RawPayload,
			&i.FetchedAt,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnprocessedRawEventsByProject = `-- name: ListUnprocessedRawEventsByProject :many
SELECT id, gitlab_event_id, project_id, issue_iid, event_type, raw_payload, fetched_at, processed, created_at FROM raw_events
WHERE processed = FALSE AND project_id = $1
ORDER BY fetched_at ASC
LIMIT $2
`

type ListUnprocessedRawEventsByProjectParams struct {
	ProjectID int32 `json:"project_id"`
	Limit     int32 `json:"limit"`
}

// Lista eventos nao processados de um projeto especifico.
func (q *Queries) ListUnprocessedRawEventsByProject(ctx context.Context, arg ListUnprocessedRawEventsByProjectParams) ([]RawEvent, error) {
	rows, err := q.db.Query(ctx, listUnprocessedRawEventsByProject, arg.ProjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawEvent{}
	for rows.Next() {
		var i RawEvent
		if err := rows.Scan(
			&i.ID,
			&i.GitlabEventID,
			&i.ProjectID,
			&i.IssueIid,
			&i.EventType,
			&i.RawPayload,
			&i.FetchedAt,
			&i.Processed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRawEventProcessed = `-- name: MarkRawEventProcessed :exec
UPDATE raw_events SET processed = TRUE WHERE id = $1
`

// Marca evento como processado apos transformacao Silver.
func (q *Queries) MarkRawEventProcessed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markRawEventProcessed, id)
	return err
}

const markRawEventsProcessedBatch = `-- name: MarkRawEventsProcessedBatch :exec
UPDATE raw_events SET processed = TRUE WHERE id = ANY($1::bigint[])
`

// Marca multiplos eventos como processados.
func (q *Queries) MarkRawEventsProcessedBatch(ctx context.Context, dollar_1 []int64) error {
	_, err := q.db.Exec(ctx, markRawEventsProcessedBatch, dollar_1)
	return err
}
