// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_projects.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRawProject = `-- name: GetRawProject :one
SELECT id, name, path, last_synced_at, raw_metadata, created_at, updated_at FROM raw_projects WHERE id = $1
`

func (q *Queries) GetRawProject(ctx context.Context, id int32) (RawProject, error) {
	row := q.db.QueryRow(ctx, getRawProject, id)
	var i RawProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastSyncedAt,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRawProjects = `-- name: ListRawProjects :many
SELECT id, name, path, last_synced_at, raw_metadata, created_at, updated_at FROM raw_projects ORDER BY name
`

// Lista todos os projetos Bronze, ordenados por nome.
func (q *Queries) ListRawProjects(ctx context.Context) ([]RawProject, error) {
	rows, err := q.db.Query(ctx, listRawProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawProject{}
	for rows.Next() {
		var i RawProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.LastSyncedAt,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRawProjectsDueSync = `-- name: ListRawProjectsDueSync :many
SELECT id, name, path, last_synced_at, raw_metadata, created_at, updated_at FROM raw_projects
WHERE last_synced_at < $1
ORDER BY last_synced_at ASC
`

// Lista projetos que precisam de sync (last_synced_at antes do threshold).
func (q *Queries) ListRawProjectsDueSync(ctx context.Context, lastSyncedAt pgtype.Timestamptz) ([]RawProject, error) {
	rows, err := q.db.Query(ctx, listRawProjectsDueSync, lastSyncedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RawProject{}
	for rows.Next() {
		var i RawProject
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.LastSyncedAt,
			&i.RawMetadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRawProjectLastSynced = `-- name: UpdateRawProjectLastSynced :exec
UPDATE raw_projects
SET last_synced_at = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateRawProjectLastSyncedParams struct {
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
	ID           int32              `json:"id"`
}

// Atualiza o cursor de sincronizacao apos extração Bronze bem-sucedida.
func (q *Queries) UpdateRawProjectLastSynced(ctx context.Context, arg UpdateRawProjectLastSyncedParams) error {
	_, err := q.db.Exec(ctx, updateRawProjectLastSynced, arg.LastSyncedAt, arg.ID)
	return err
}

const upsertRawProject = `-- name: UpsertRawProject :one
INSERT INTO raw_projects (id, name, path, raw_metadata, last_synced_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    path = EXCLUDED.path,
    raw_metadata = EXCLUDED.raw_metadata,
    updated_at = NOW()
RETURNING id, name, path, last_synced_at, raw_metadata, created_at, updated_at
`

type UpsertRawProjectParams struct {
	ID           int32              `json:"id"`
	Name         string             `json:"name"`
	Path         string             `json:"path"`
	RawMetadata  []byte             `json:"raw_metadata"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

// Insere ou atualiza um projeto na camada Bronze.
// Usado pelo Discovery Service ao descobrir projetos novos.
func (q *Queries) UpsertRawProject(ctx context.Context, arg UpsertRawProjectParams) (RawProject, error) {
	row := q.db.QueryRow(ctx, upsertRawProject,
		arg.ID,
		arg.Name,
		arg.Path,
		arg.RawMetadata,
		arg.LastSyncedAt,
	)
	var i RawProject
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.LastSyncedAt,
		&i.RawMetadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
