// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: state_mapping.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getStateMappingByLabel = `-- name: GetStateMappingByLabel :one
SELECT id, gitlab_label_name, canonical_state, description, created_at, updated_at FROM state_mapping WHERE gitlab_label_name = $1
`

func (q *Queries) GetStateMappingByLabel(ctx context.Context, gitlabLabelName string) (StateMapping, error) {
	row := q.db.QueryRow(ctx, getStateMappingByLabel, gitlabLabelName)
	var i StateMapping
	err := row.Scan(
		&i.ID,
		&i.GitlabLabelName,
		&i.CanonicalState,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStateMappings = `-- name: ListStateMappings :many
SELECT id, gitlab_label_name, canonical_state, description, created_at, updated_at FROM state_mapping ORDER BY canonical_state, gitlab_label_name
`

// Lista todos os mapeamentos de estado. Usado pelo StateMapper no startup.
func (q *Queries) ListStateMappings(ctx context.Context) ([]StateMapping, error) {
	rows, err := q.db.Query(ctx, listStateMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StateMapping{}
	for rows.Next() {
		var i StateMapping
		if err := rows.Scan(
			&i.ID,
			&i.GitlabLabelName,
			&i.CanonicalState,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertStateMapping = `-- name: UpsertStateMapping :one
INSERT INTO state_mapping (gitlab_label_name, canonical_state, description, updated_at)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (gitlab_label_name) DO UPDATE SET
    canonical_state = EXCLUDED.canonical_state,
    description = EXCLUDED.description,
    updated_at = NOW()
RETURNING id, gitlab_label_name, canonical_state, description, created_at, updated_at
`

type UpsertStateMappingParams struct {
	GitlabLabelName string      `json:"gitlab_label_name"`
	CanonicalState  string      `json:"canonical_state"`
	Description     pgtype.Text `json:"description"`
}

func (q *Queries) UpsertStateMapping(ctx context.Context, arg UpsertStateMappingParams) (StateMapping, error) {
	row := q.db.QueryRow(ctx, upsertStateMapping, arg.GitlabLabelName, arg.CanonicalState, arg.Description)
	var i StateMapping
	err := row.Scan(
		&i.ID,
		&i.GitlabLabelName,
		&i.CanonicalState,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
