// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sync_state.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSyncState = `-- name: GetSyncState :one
SELECT id, project_id, last_synced_at, created_at, updated_at FROM sync_state
WHERE project_id = $1
LIMIT 1
`

func (q *Queries) GetSyncState(ctx context.Context, projectID int32) (SyncState, error) {
	row := q.db.QueryRow(ctx, getSyncState, projectID)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSyncState = `-- name: UpsertSyncState :one
INSERT INTO sync_state (project_id, last_synced_at, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (project_id)
DO UPDATE SET
    last_synced_at = EXCLUDED.last_synced_at,
    updated_at = NOW()
RETURNING id, project_id, last_synced_at, created_at, updated_at
`

type UpsertSyncStateParams struct {
	ProjectID    int32              `json:"project_id"`
	LastSyncedAt pgtype.Timestamptz `json:"last_synced_at"`
}

func (q *Queries) UpsertSyncState(ctx context.Context, arg UpsertSyncStateParams) (SyncState, error) {
	row := q.db.QueryRow(ctx, upsertSyncState, arg.ProjectID, arg.LastSyncedAt)
	var i SyncState
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
