// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: unknown_labels_log.sql

package repository

import (
	"context"
)

const countUnknownLabels = `-- name: CountUnknownLabels :one
SELECT COUNT(*) FROM unknown_labels_log
`

func (q *Queries) CountUnknownLabels(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnknownLabels)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listUnknownLabels = `-- name: ListUnknownLabels :many
SELECT id, label_name, occurrence_count, first_seen_at, last_seen_at FROM unknown_labels_log
ORDER BY occurrence_count DESC
`

// Lista labels desconhecidas ordenadas por frequencia (mais comuns primeiro).
func (q *Queries) ListUnknownLabels(ctx context.Context) ([]UnknownLabelsLog, error) {
	rows, err := q.db.Query(ctx, listUnknownLabels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnknownLabelsLog{}
	for rows.Next() {
		var i UnknownLabelsLog
		if err := rows.Scan(
			&i.ID,
			&i.LabelName,
			&i.OccurrenceCount,
			&i.FirstSeenAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUnknownLabel = `-- name: UpsertUnknownLabel :one
INSERT INTO unknown_labels_log (label_name, occurrence_count, first_seen_at, last_seen_at)
VALUES ($1, 1, NOW(), NOW())
ON CONFLICT (label_name) DO UPDATE SET
    occurrence_count = unknown_labels_log.occurrence_count + 1,
    last_seen_at = NOW()
RETURNING id, label_name, occurrence_count, first_seen_at, last_seen_at
`

// Registra ou incrementa contagem de uma label desconhecida.
func (q *Queries) UpsertUnknownLabel(ctx context.Context, labelName string) (UnknownLabelsLog, error) {
	row := q.db.QueryRow(ctx, upsertUnknownLabel, labelName)
	var i UnknownLabelsLog
	err := row.Scan(
		&i.ID,
		&i.LabelName,
		&i.OccurrenceCount,
		&i.FirstSeenAt,
		&i.LastSeenAt,
	)
	return i, err
}
